export const TAX_AUDIT_DISCLAIMER_VERSION = 'TAX_AUDIT_DISCLAIMER_V1' as const;

export type TaxAuditDisclaimerSection = {
  id: string;
  title: string;
  statement: string;
  displayOrder: number;
};

export const TAX_AUDIT_DISCLAIMER_SECTIONS: TaxAuditDisclaimerSection[] = [
  {
    id: 'purpose_of_tool',
    title: 'A. Purpose of the Tool',
    statement:
      'This Tax Audit module is intended to assist members in carrying out tax audit procedures in a structured and documented manner. It is an aid to professional work and not a substitute for the auditor\'s independent judgment.',
    displayOrder: 10,
  },
  {
    id: 'professional_judgment',
    title: 'B. Professional Judgment',
    statement:
      'The auditor shall independently evaluate the facts, records, explanations, applicable law, Guidance Notes, Standards on Auditing and other professional requirements before forming any conclusion or issuing any report.',
    displayOrder: 20,
  },
  {
    id: 'auditor_responsibility',
    title: 'C. Auditor Responsibility',
    statement:
      'The responsibility for accepting the engagement, performing audit procedures, obtaining sufficient appropriate evidence, reporting particulars in Form 3CA/3CB/3CD and issuing the final tax audit report remains solely with the auditor.',
    displayOrder: 30,
  },
  {
    id: 'verification_with_law',
    title: 'D. Verification with Law and ICAI Guidance',
    statement:
      'The user must verify all outputs, checklists, clause responses and readiness indicators with the Income-tax Act, Income-tax Rules, relevant CBDT notifications and circulars, ICAI Guidance Notes and other applicable pronouncements as amended from time to time.',
    displayOrder: 40,
  },
  {
    id: 'data_responsibility',
    title: 'E. Data and Input Responsibility',
    statement:
      'The accuracy and completeness of results depend on the accuracy and completeness of data, records, documents and explanations entered or uploaded by the user.',
    displayOrder: 50,
  },
  {
    id: 'automated_outputs',
    title: 'F. Limitation of Automated Outputs',
    statement:
      'Any computation, warning, readiness indicator, checklist status or structured response generated by the tool is indicative and requires professional review. The tool does not provide legal opinion, tax advice or final audit conclusion by itself.',
    displayOrder: 60,
  },
  {
    id: 'documentation_evidence',
    title: 'G. Documentation and Evidence',
    statement:
      'The auditor is responsible for maintaining adequate working papers, evidence, management representations and review documentation in accordance with applicable Standards on Auditing and professional requirements.',
    displayOrder: 70,
  },
  {
    id: 'limitation_of_use',
    title: 'H. Limitation of Use',
    statement:
      'The tool is designed to assist members in standardising and documenting tax audit work. It does not guarantee detection of all errors, omissions, frauds, non-compliances or reporting matters.',
    displayOrder: 80,
  },
  {
    id: 'final_report_responsibility',
    title: 'I. Final Report Responsibility',
    statement:
      'Before signing or uploading the tax audit report, the auditor must independently review all particulars, qualifications, observations and supporting evidence.',
    displayOrder: 90,
  },
];
